name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Läuft täglich um Mitternacht
  workflow_dispatch: # Manuelles Ausführen möglich

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: EministarVR
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit and Push Snake Animation
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update Snake Animation"
          git push
